spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/twitter
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
logging:
  level:
    org:
      springframework:
        security: debug


