version: '3'
services:
  postges:
    image: postgres:13.3
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twitter
    ports:
      - "54321:5432"
  sonarqube:
    image: sonarqube:10.2.1-community
    ports:
      - "9000:9000"